[package]
authors = ["sundy-li <sundyli@apache.org>>"]
categories = ["command-line-utilities"]
description = "Replace with description"
documentation = "https://docs.rs/arrow_cli"
repository = "https://github.com/sundy-li/arrow_cli"
edition = "2021"
license = "Apache-2.0"
name = "arrow_cli"
version = "0.0.1"

[dependencies]
clap = { version = "4.1.13", features = ["derive", "cargo"] }
shlex = "1.1.0"
isatty = "0.1.9"
rustyline = "11.0.0"
